// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkYIuzNU5x9-9jRMByxxCKh2JQjPISHvw',
    appId: '1:304593493789:web:65fd91553b8c57e2a7cbf4',
    messagingSenderId: '304593493789',
    projectId: 'app-movil-mascotas',
    authDomain: 'app-movil-mascotas.firebaseapp.com',
    storageBucket: 'app-movil-mascotas.firebasestorage.app',
    measurementId: 'G-DX85F8WHJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwrP2dmHimHF-jfCZ7dW3h1SvpebNUzjY',
    appId: '1:304593493789:android:a65a9f56188b4802a7cbf4',
    messagingSenderId: '304593493789',
    projectId: 'app-movil-mascotas',
    storageBucket: 'app-movil-mascotas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBinCgQGBbGyvIbQ-rk4yijKl5ihxkkAyc',
    appId: '1:304593493789:ios:7a5275bcbaed7522a7cbf4',
    messagingSenderId: '304593493789',
    projectId: 'app-movil-mascotas',
    storageBucket: 'app-movil-mascotas.firebasestorage.app',
    iosBundleId: 'com.example.easypet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBinCgQGBbGyvIbQ-rk4yijKl5ihxkkAyc',
    appId: '1:304593493789:ios:7a5275bcbaed7522a7cbf4',
    messagingSenderId: '304593493789',
    projectId: 'app-movil-mascotas',
    storageBucket: 'app-movil-mascotas.firebasestorage.app',
    iosBundleId: 'com.example.easypet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkYIuzNU5x9-9jRMByxxCKh2JQjPISHvw',
    appId: '1:304593493789:web:aa88bdfb207afc4ba7cbf4',
    messagingSenderId: '304593493789',
    projectId: 'app-movil-mascotas',
    authDomain: 'app-movil-mascotas.firebaseapp.com',
    storageBucket: 'app-movil-mascotas.firebasestorage.app',
    measurementId: 'G-F53VX2XBHY',
  );

}